### ISSUE TITLE
Error parsing KingOfSat page

### ISSUE THREAD

**Issue by NightSkySK** [andrzejlisek/SatRTV#1]
Initial configuration:
```
 0 # 13.0E - Hot Bird
 1   19.2E - Astra

Band 1 ( 3400MHz -  4200MHz) - no
Band 2 (10700MHz - 12750MHz) - yes
Band 3 (18200MHz - 22200MHz) - no

All channels
Transponders with channels
Channel type: TV
```
Execution:

```
DOWNLOAD 1
Downloading 0...OK

PARSE 1
Parsing 0...
Wyjątek nieobsłużony: System.Exception: XXX
   w SatRTV.AppCoreSat_1KingOfSat.ParseDiv(HtmlNode DivN, Int32 _i, StreamWriter FS2W, Boolean TypeByPID, String[] SatTrans)
   w SatRTV.AppCoreSat_1KingOfSat.Parse(Int32 I, Boolean TypeByPID)
   w SatRTV.Program.Main(String[] args)
```

`ChanData000.txt` is created correctly during parsing
`TransData000.txt` is created but remain empty.

[Data1.zip](https://github.com/andrzejlisek/SatRTV/files/8203798/Data1.zip)

**Comment by andrzejlisek** [comment]
There is problem in language code parsing.

Today, on the KingofSat, there is non-standard language info in one place. The language parser detects two strings to distinguish language code and soundtrack number. The non-standard cases always causes the problem and there is difficult to implement all possible non-standard cases.

The sountrack number consists of digits only and the language code consists of letters and "-", "." characters. Problably I will include "?" as next character as character of language code in next release, but on the other hand, such cases causes rarely.

By analyzing ChanData000.txt, you can find, where is the error, by last line of the file.

If you open the saved HTML page, you can find both non-standard languages by finding following phrase:
"???"
You have to manually remove the "???" words from the HTML file and try again parsing.

This exception was raised from the line 244 of the AppCoreSat_1KingOfSat.cs file.

**Comment by NightSkySK** [comment]
Thank you!
