### ISSUE TITLE
FlySat links to be updated, Parsing doesn't work

### ISSUE THREAD

**Issue by NightSkySK** [andrzejlisek/SatRTV#2]
Original links from config.txt for FlySat doesn't work anymore. Config.txt should be updated to following links.
HotBird: `https://www.flysat.com/en/satellite/position/13-e`
Astra: `https://www.flysat.com/en/satellite/position/19-2-e`

Parsing doesn't work anymore for those pages

**Comment by andrzejlisek** [comment]
Thank you for the information. The provided Config.txt file is sample and the user should make sure sure, that provided URLs are correct. The user can define other satellites apart from Hot Bird and Astra.

Simply, you have to replace the URLs in file with actual URLs and try download.

In future release, the sample URLs will be updated.
